/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lab11_Lab11 */

#ifndef _Included_lab11_Lab11
#define _Included_lab11_Lab11
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lab11_Lab11
 * Method:    Cbqrt
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_lab11_Lab11_Cbqrt
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     lab11_Lab11
 * Method:    Sin
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_lab11_Lab11_Sin
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     lab11_Lab11
 * Method:    ln
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_lab11_Lab11_ln
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     lab11_Lab11
 * Method:    matrSumm8
 * Signature: ([[I)I
 */
JNIEXPORT jint JNICALL Java_lab11_Lab11_matrSumm8
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     lab11_Lab11
 * Method:    matrSumm10
 * Signature: ([[I)I
 */
JNIEXPORT jint JNICALL Java_lab11_Lab11_matrSumm10
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
